language: python
python:
  - "3.6"

branches:
  except:
    - pr_matrix


env:
  global:
    - ADDON_CHECK_PATH=$HOME/addon-check/
    - ADDON_PYTHON_PATH=$TRAVIS_BUILD_DIR/resources/lib/
    - KODI_MIN_VERSION=matrix

before_install:
  - |
    git clone https://github.com/xbmc/addon-check $ADDON_CHECK_PATH

install:
  - pip install isort
  - pip install pylint
  - pip install $ADDON_CHECK_PATH

before_script:
  - |
    rm -f .gitattributes
    mv .pylintrc $HOME
    cd $HOME

script:
  - kodi-addon-checker $TRAVIS_BUILD_DIR --branch=$KODI_MIN_VERSION
  - pylint $ADDON_PYTHON_PATH
  - isort $TRAVIS_BUILD_DIR --diff
