name: Add-on Validations

on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:

  addon-validations:
    runs-on: ubuntu-latest

    name: Add-on Validations

    steps:
      - name: Set up Python v3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Checkout Add-on
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}

      - name: Checkout kodi-addon-checker
        uses: actions/checkout@v2
        with:
          repository: xbmc/addon-check
          path: addon-check

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          python -m pip install isort
          python -m pip install pylint
          python -m pip install addon-check/

      - name: Staging
        run: |
          rm -rf LICENSES/
          rm -f .gitattributes
          cp -t ${HOME} .isort.cfg .pylintrc
        working-directory: ${{ github.event.repository.name }}

      - name: Kodi Add-on Checker
        id: kodi-addon-checker
        run: |
          kodi-addon-checker ${{ github.event.repository.name }} --branch=matrix

      - name: Pylint
        id: pylint
        run: |
          pylint resources/lib/
        working-directory: ${{ github.event.repository.name }}

      - name: isort
        id: isort
        run: |
          isort . --diff
        working-directory: ${{ github.event.repository.name }}
